### ISSUE TITLE
Cassandra fails to come up if the Cluster Manager is restarted whilst it's joining the cluster

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/homestead#390]
#### Symptoms
Cassandra was continuously failing to start.

From `/var/log/cassandra/system.log`:

```
ERROR [main] 2016-11-28 18:56:27,905 CassandraDaemon.java:583 - Exception encountered during startup
java.lang.RuntimeException: A node with address /10.225.166.22 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:544) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:794) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:726) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:617) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:391) [apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:566) [apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:655) [apache-cassandra-2.1.15.jar:2.1.15]
```

The following from the Cluster Manager logs might be interesting...

```
28-11-2016 18:55:03.261 UTC INFO cassandra_plugin.py:117 (thread CassandraPlugin): Cassandra seeds list is 10.225.166.21
28-11-2016 18:55:03.444 UTC INFO cassandra_plugin.py:151 (thread CassandraPlugin): Restarting Cassandra
28-11-2016 18:55:03.453 UTC ERROR plugin_utils.py:70 (thread CassandraPlugin): Command start-stop-daemon -K -p /var/run/cassandra/cassandra.pid -R TERM/30/KILL/5 failed with return code 1, stdout "No process in pidfile '/var/run/cassandra/cassandra.pid' found running; none killed.\n", and stderr ''
28-11-2016 18:55:03.453 UTC INFO cassandra_plugin.py:167 (thread CassandraPlugin): Stopped Cassandra while changing config files
28-11-2016 18:55:03.453 UTC WARNING cassandra_plugin.py:170 (thread CassandraPlugin): Deleting /var/lib/cassandra - this is normal on initial clustering
28-11-2016 18:55:03.478 UTC INFO cassandra_plugin.py:236 (thread CassandraPlugin): Waiting for Cassandra to come up...
28-11-2016 18:55:20.280 UTC INFO main.py:103 (thread MainThread): Handling SIGTERM
28-11-2016 18:55:20.281 UTC INFO main.py:105 (thread MainThread): <metaswitch.clearwater.cluster_manager.etcd_synchronizer.EtcdSynchronizer object at 0x7f43e9bce890> exiting cleanly
28-11-2016 18:55:29.961 UTC INFO cassandra_plugin.py:244 (thread CassandraPlugin): Still waiting for Cassandra to come up...
28-11-2016 18:55:50.169 UTC INFO cassandra_plugin.py:244 (thread CassandraPlugin): Still waiting for Cassandra to come up...
28-11-2016 18:55:59.785 UTC INFO utils.py:441 (thread MainThread): Acquired exclusive lock on /var/run/clearwater-cluster-manager.pid.lockfile
28-11-2016 18:55:59.785 UTC INFO plugin_loader.py:51 (thread MainThread): Inspecting cassandra_plugin.py
28-11-2016 18:55:59.816 UTC INFO plugin_loader.py:59 (thread MainThread): Loading cassandra_plugin.py
28-11-2016 18:55:59.816 UTC INFO plugin_loader.py:61 (thread MainThread): Loaded cassandra_plugin.py successfully
28-11-2016 18:55:59.816 UTC INFO plugin_loader.py:51 (thread MainThread): Inspecting cassandra_plugin.pyc
28-11-2016 18:55:59.817 UTC INFO main.py:215 (thread MainThread): Loaded plugin <cassandra_plugin.CassandraPlugin object at 0x7f6c01e6b850>
28-11-2016 18:55:59.822 UTC INFO common_etcd_synchronizer.py:194 (thread CassandraPlugin): Read value {"10.225.166.21": "normal, config changed", "10.225.166.22": "joining, acknowledged change"} from etcd, comparing to last value None
28-11-2016 18:55:59.822 UTC INFO etcd_synchronizer.py:72 (thread CassandraPlugin): Got new state {"10.225.166.21": "normal, config changed", "10.225.166.22": "joining, acknowledged change"} from etcd
28-11-2016 18:55:59.822 UTC INFO synchronization_fsm.py:131 (thread CassandraPlugin): Entered state machine for 10.225.166.22 with local state joining, acknowledged change, cluster state joining, config changing and cluster view {u'10.225.166.21': u'normal, config changed', u'10.225.166.22': u'joining, acknowledged change'}
28-11-2016 18:55:59.822 UTC INFO synchronization_fsm.py:49 (thread CassandraPlugin): Calling plugin method CassandraPlugin.on_startup
28-11-2016 18:55:59.823 UTC INFO synchronization_fsm.py:49 (thread CassandraPlugin): Calling plugin method CassandraPlugin.on_joining_cluster
28-11-2016 18:55:59.830 UTC INFO alarms.py:337 (thread CassandraPlugin): Imported /usr/share/clearwater/bin/alarms.py
28-11-2016 18:55:59.831 UTC INFO cassandra_plugin.py:117 (thread CassandraPlugin): Cassandra seeds list is 10.225.166.21
28-11-2016 18:55:59.896 UTC INFO cassandra_plugin.py:151 (thread CassandraPlugin): Restarting Cassandra
```

All the buzz is around the following scenario:
* Cluster Manager killed the local Cassandra process, deleted `/var/lib/cassandra` and then started up the Cassandra process again with the correct seeds list (so that it would cluster).
* Cluster Manager was killed by the Queue Manager because someone ran `upload_shared_config` on another node.
* The Cassandra plugin waited for Cassandra to come back up before terminating, but the Cluster Manager never wrote to etcd to put the node into state `normalg`.
* Once the Cluster Manager restarted, it read that this node was still in the state `joining, acknowledged change` and so it again killed the local Cassandra process, deleted `/var/lib/cassandra` and then started up the Cassandra process again with the correct seeds list (so that it would cluster). Unfortunately this time the cluster already thought they had this node and said "no can do".

A diags bundle is attached.

#### Impact
Well obviously Cassandra wasn't running on one of my nodes. You could argue that the impact is lower because I had to run `upload_shared_config` before the node had properly come up, but I'd argue in turn that a) when am I allowed to run `upload_shared_config`? and b) can we hit this kind of window in other scenarios?

#### Release and environment 
The inimitable CC-homestead-10.0.0-20161116-~255.00.0.ova

#### Steps to reproduce
Spin up 2 Sprouts and 2 Homestead. Run `upload_shared_config` to trigger Cluster Manager being restarted whilst it's trying to bring up a Cassandra.

**Comment by johadalin** [comment]
The changes in https://github.com/Metaswitch/clearwater-etcd-plugins/pull/20, and associated changes, should resolve this. Passing back to test.

**Comment by rkd-msw** [comment]
@johadalin - pass stuff back to the original raiser, please, not me.

**Comment by johadalin** [comment]
@rkd-msw sure thing :+1:

**Comment by graemerobertson** [comment]
I'm not going to lie, I can't be bothered to try and repro this. I'm pleased you've fixed it.
